grav = 0.2;
xvel = 0
yvel = 0
runspeed = 5
gravityCap = 5;
jumpBaseCount = 2;
jumpCount = 0;
dashBaseCount = 1;
dashCount = 0;
pFacing = 1;
stateCurrent = pState.idle;
stateLast = pState.idle;
timerDash = 0.2 * 60; //seconds * 60